// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package linkdb

import (
	"time"
)

type Link struct {
	ID        int64
	Code      string
	TargetURL string
	CreatedAt time.Time
}
