// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package linkdb

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (code, target_url)
VALUES ($1, $2)
RETURNING id, code, target_url, created_at
`

type CreateLinkParams struct {
	Code      string
	TargetURL string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Code, arg.TargetURL)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TargetURL,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT id, code, target_url, created_at
FROM links
WHERE code = $1
`

func (q *Queries) GetLinkByCode(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCode, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TargetURL,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, code, target_url, created_at
FROM links
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListLinks(ctx context.Context, limit int32) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TargetURL,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
